# SCRUMIT
## This document is carries code for data exploration and cleaning and mostly presenting a summary stats for all those datasets
# Datasets - OpenSanctions - link - https://www.opensanctions.org/datasets/default/

### Importing packages

As usual we begin by importing the necessary packages and functions.

In [4]:
#importing and reading the dataset

from pathlib import Path

DATA_PATH = Path("../../data/raw/entities.ftm.json")
print(DATA_PATH.exists())

from pathlib import Path
import json
import pandas as pd

DATA_PATH = Path("../../data/raw/entities.ftm.json")

with open(DATA_PATH, "r", encoding="utf-8") as f:
    first_line = f.readline()

record = json.loads(first_line)
record

True

{'id': 'NK-2229ydxkHNa5AcDp9d6jt3',
 'caption': 'Occupancy',
 'schema': 'Occupancy',
 'referents': ['wd-e6fbb0b4a5647317a4610efb1f52003ec1bb437e',
  'wd-9e8d9b8e4656f484e477fee7758b9ea9e19e4014',
  'wd-4f78058be60118f60f58a1b7a3a98f37a29b52e7'],
 'datasets': ['wd_peps', 'wd_categories'],
 'first_seen': '2025-12-09T10:14:09',
 'last_seen': '2026-03-02T00:12:02',
 'last_change': '2026-01-16T00:12:01',
 'properties': {'startDate': ['2015-04-02'],
  'holder': ['Q63765953'],
  'post': ['Q63758900']},
 'target': False}

In [5]:
#recording the first 50 rows
rows = []

with open(DATA_PATH, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        rows.append(json.loads(line))
        if i == 49:   # load first 50 records
            break

df = pd.DataFrame(rows)
df.head()

,id,caption,schema,referents,datasets,first_seen,last_seen,last_change,properties,target,origin
0,NK-2229ydxkHNa5AcDp9d6jt3,Occupancy,Occupancy,"[wd-e6fbb0b4a5647317a4610efb1f52003ec1bb437e, ...","[wd_peps, wd_categories]",2025-12-09T10:14:09,2026-03-02T00:12:02,2026-01-16T00:12:01,"{'startDate': ['2015-04-02'], 'holder': ['Q637...",False,NaN
1,NK-222VHospCrfMcFWpjLyidR,Occupancy,Occupancy,"[wd-91fe4b57c4e2a081cad42323910fee342d5fbf85, ...","[wd_peps, wd_categories]",2025-12-09T10:14:09,2026-03-02T00:12:02,2026-01-16T00:12:01,"{'holder': ['Q24018002'], 'startDate': ['2024-...",False,NaN
2,NK-222ZEryAX3VL524jzxqth9,Occupancy,Occupancy,"[wd-7248f3fb86aaec96147d8edd35979b921011cd0c, ...","[wd_peps, wd_categories]",2025-12-09T10:14:09,2026-03-02T00:12:02,2026-01-16T00:12:01,"{'holder': ['Q63764445'], 'startDate': ['2015-...",False,NaN
3,NK-222iTgdqGfVvpwiD5pXoAs,Occupancy,Occupancy,"[wd-f6025e68206dc8f30197edb8e63a5916ed6f7aba, ...","[wd_peps, wd_categories]",2025-07-29T14:00:16,2026-03-02T00:12:02,2026-01-16T00:12:01,"{'post': ['Q65494724'], 'startDate': ['2017-01...",False,NaN
4,NK-223Aofhpkvj6sYRhh8xD4z,Occupancy,Occupancy,"[wd-f60ffbf5d58013618878b722a00dbd98b14d4b40, ...","[wd_peps, wd_categories]",2025-12-09T10:14:09,2026-03-02T00:12:02,2026-01-16T00:12:01,"{'startDate': ['2017-01-10'], 'post': ['Q66500...",False,NaN

In [6]:
#since data is big, we need pandas
import json
import pandas as pd
from pathlib import Path
from collections import defaultdict

In [11]:
#set dataset path 
DATA_PATH = Path("../../data/raw/entities.ftm.json")
print(DATA_PATH.exists())

#inspecting the record
with open(DATA_PATH, "r", encoding="utf-8") as f:
    first_line = f.readline()

record = json.loads(first_line)
record

True

{'id': 'NK-2229ydxkHNa5AcDp9d6jt3',
 'caption': 'Occupancy',
 'schema': 'Occupancy',
 'referents': ['wd-e6fbb0b4a5647317a4610efb1f52003ec1bb437e',
  'wd-9e8d9b8e4656f484e477fee7758b9ea9e19e4014',
  'wd-4f78058be60118f60f58a1b7a3a98f37a29b52e7'],
 'datasets': ['wd_peps', 'wd_categories'],
 'first_seen': '2025-12-09T10:14:09',
 'last_seen': '2026-03-02T00:12:02',
 'last_change': '2026-01-16T00:12:01',
 'properties': {'startDate': ['2015-04-02'],
  'holder': ['Q63765953'],
  'post': ['Q63758900']},
 'target': False}

In [12]:
from pathlib import Path
import json
from collections import Counter

DATA_PATH = Path("../../data/raw/entities.ftm.json")

property_counter = Counter()
schema_counter = Counter()
total_rows = 0

with open(DATA_PATH, "r", encoding="utf-8") as f:
    for line in f:
        record = json.loads(line)
        total_rows += 1
        
        schema = record.get("schema")
        if schema is not None:
            schema_counter[schema] += 1
        
        properties = record.get("properties", {})
        property_counter.update(properties.keys())

print("Total rows:", total_rows)
print("Total unique property keys:", len(property_counter))
print("\nTop 30 most common property keys:")
for key, count in property_counter.most_common(30):
    print(f"{key}: {count}")

Total rows: 4168476
Total unique property keys: 165

Top 30 most common property keys:
country: 2133199
name: 1970118
topics: 1410962
startDate: 1317625
sourceUrl: 950447
holder: 876421
post: 856840
firstName: 733389
lastName: 691275
classification: 630742
entity: 623416
authority: 610299
status: 598397
position: 499227
endDate: 483254
address: 473391
birthDate: 468532
notes: 455011
gender: 422092
alias: 409958
programId: 401459
wikidataId: 388946
citizenship: 369878
createdAt: 369565
isin: 357007
program: 355647
issuer: 345700
authorityId: 297640
provisions: 267107
summary: 259100

In [13]:
#inspct the propertis as table

property_summary = (
    pd.DataFrame(property_counter.items(), columns=["property", "count"])
    .sort_values("count", ascending=False)
    .reset_index(drop=True)
)

property_summary["share_pct"] = property_summary["count"] / total_rows * 100
property_summary.head(30)

          property    count  share_pct
0          country  2133199  51.174554
1             name  1970118  47.262309
2           topics  1410962  33.848390
3        startDate  1317625  31.609274
4        sourceUrl   950447  22.800827
5           holder   876421  21.024974
6             post   856840  20.555234
7        firstName   733389  17.593696
8         lastName   691275  16.583399
9   classification   630742  15.131237
10          entity   623416  14.955490
11       authority   610299  14.640818
12          status   598397  14.355294
13        position   499227  11.976247
14         endDate   483254  11.593062
15         address   473391  11.356453
16       birthDate   468532  11.239887
17           notes   455011  10.915524
18          gender   422092  10.125811
19           alias   409958   9.834721
20       programId   401459   9.630834
21      wikidataId   388946   9.330652
22     citizenship   369878   8.873219
23       createdAt   369565   8.865710
24            isin   357007   8.564449
25         program   355647   8.531823
26          issuer   345700   8.293199
27     authorityId   297640   7.140259
28      provisions   267107   6.407785
29         summary   259100   6.215701

In [14]:
#inspect schemas

schema_summary = (
    pd.DataFrame(schema_counter.items(), columns=["schema", "count"])
    .sort_values("count", ascending=False)
    .reset_index(drop=True)
)

schema_summary["share_pct"] = schema_summary["count"] / total_rows * 100
schema_summary.head(20)

            schema    count  share_pct
0           Person  1121712  26.909403
1        Occupancy   856840  20.555234
2         Sanction   610298  14.640794
3         Security   357082   8.566248
4          Company   234456   5.624502
5        Ownership   227029   5.446331
6         Position   183120   4.392972
7     Directorship   130838   3.138749
8     Organization   101953   2.445810
9      LegalEntity    86259   2.069317
10          Family    81435   1.953592
11     UnknownLink    43847   1.051871
12      Succession    36073   0.865376
13         Address    30858   0.740271
14    CryptoWallet    13674   0.328034
15   Documentation    13118   0.314695
16        Passport    11007   0.264053
17          Vessel     8913   0.213819
18  Identification     6770   0.162409
19         Article     3470   0.083244

In [15]:
#keeping those properties that comes 1% of rows
common_properties = property_summary[property_summary["share_pct"] >= 1]["property"].tolist()
common_properties[:50]

['country',
 'name',
 'topics',
 'startDate',
 'sourceUrl',
 'holder',
 'post',
 'firstName',
 'lastName',
 'classification',
 'entity',
 'authority',
 'status',
 'position',
 'endDate',
 'address',
 'birthDate',
 'notes',
 'gender',
 'alias',
 'programId',
 'wikidataId',
 'citizenship',
 'createdAt',
 'isin',
 'program',
 'issuer',
 'authorityId',
 'provisions',
 'summary',
 'currency',
 'innCode',
 'listingDate',
 'programUrl',
 'political',
 'reason',
 'asset',
 'owner',
 'birthPlace',
 'legalForm',
 'role',
 'jurisdiction',
 'fatherName',
 'description',
 'incorporationDate',
 'taxNumber',
 'sharesCount',
 'ogrnCode',
 'kppCode',
 'percentage']

In [16]:
#defining a flattening function
def flatten_record(record):
    properties = record.get("properties", {})
    
    flat = {
        "id": record.get("id"),
        "caption": record.get("caption"),
        "schema": record.get("schema"),
        "first_seen": record.get("first_seen"),
        "last_seen": record.get("last_seen"),
        "last_change": record.get("last_change"),
        "target": record.get("target"),
        "datasets": ", ".join(record.get("datasets", [])) if record.get("datasets") else None,
        "referents_count": len(record.get("referents", [])) if record.get("referents") else 0,
    }
    
    # Flatten selected properties
    for key, value in properties.items():
        if isinstance(value, list):
            flat[key] = ", ".join(str(v) for v in value) if value else None
        else:
            flat[key] = value
    
    return flat

In [22]:
#flattening a small sample first

rows = []

with open(DATA_PATH, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        record = json.loads(line)
        rows.append(flatten_record(record))

        if i == 999:   # first 1000 rows
            break

df_sample = pd.DataFrame(rows)

print(df_sample.shape)
df_sample.head()

#inspect variables
#df_sample.columns

(1000, 103)

,id,caption,schema,first_seen,last_seen,last_change,target,datasets,referents_count,startDate,...,mmsi,vatCode,wikidataId,percentage,sharesCount,mainCountry,icijId,postalCode,model,serialNumber
0,NK-2229ydxkHNa5AcDp9d6jt3,Occupancy,Occupancy,2025-12-09T10:14:09,2026-03-02T00:12:02,2026-01-16T00:12:01,False,"wd_peps, wd_categories",3,2015-04-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NK-222VHospCrfMcFWpjLyidR,Occupancy,Occupancy,2025-12-09T10:14:09,2026-03-02T00:12:02,2026-01-16T00:12:01,False,"wd_peps, wd_categories",2,2024-11-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NK-222ZEryAX3VL524jzxqth9,Occupancy,Occupancy,2025-12-09T10:14:09,2026-03-02T00:12:02,2026-01-16T00:12:01,False,"wd_peps, wd_categories",3,2015-04-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NK-222iTgdqGfVvpwiD5pXoAs,Occupancy,Occupancy,2025-07-29T14:00:16,2026-03-02T00:12:02,2026-01-16T00:12:01,False,"wd_peps, wd_categories",2,2017-01-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NK-223Aofhpkvj6sYRhh8xD4z,Occupancy,Occupancy,2025-12-09T10:14:09,2026-03-02T00:12:02,2026-01-16T00:12:01,False,"wd_peps, wd_categories",3,2017-01-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#to check all flatten variables
df_sample.columns.tolist()

['id',
 'caption',
 'schema',
 'first_seen',
 'last_seen',
 'last_change',
 'target',
 'datasets',
 'referents_count',
 'startDate',
 'holder',
 'post',
 'name',
 'sourceUrl',
 'opencorporatesUrl',
 'alias',
 'sector',
 'registrationNumber',
 'country',
 'topics',
 'addressEntity',
 'address',
 'programId',
 'createdAt',
 'notes',
 'uniqueEntityId',
 'predecessor',
 'successor',
 'ogrnCode',
 'kppCode',
 'incorporationDate',
 'innCode',
 'jurisdiction',
 'legalForm',
 'birthPlace',
 'nationality',
 'birthDate',
 'eyeColor',
 'hairColor',
 'gender',
 'lastName',
 'firstName',
 'asset',
 'owner',
 'role',
 'endDate',
 'status',
 'phone',
 'email',
 'website',
 'modifiedAt',
 'idNumber',
 'taxNumber',
 'classification',
 'position',
 'npiCode',
 'middleName',
 'grossRegisteredTonnage',
 'flag',
 'type',
 'imoNumber',
 'buildDate',
 'relative',
 'person',
 'relationship',
 'description',
 'okpoCode',
 'program',
 'citizenship',
 'permId',
 'weakAlias',
 'swiftBic',
 'giiNumber',
 'dissolutionDate',
 'fatherName',
 'motherName',
 'passportNumber',
 'brightQueryOrgId',
 'brightQueryId',
 'full',
 'publisher',
 'director',
 'organization',
 'title',
 'leiCode',
 'keywords',
 'region',
 'city',
 'street',
 'pastFlags',
 'previousName',
 'deadweightTonnage',
 'callSign',
 'mmsi',
 'vatCode',
 'wikidataId',
 'percentage',
 'sharesCount',
 'mainCountry',
 'icijId',
 'postalCode',
 'model',
 'serialNumber']

In [24]:
#check entity type
df_sample["schema"].value_counts()

schema
Occupancy       662
Person          102
Company          78
Succession       69
Organization     33
LegalEntity      21
Family           12
Ownership         8
Vessel            7
Directorship      4
Address           3
Airplane          1
Name: count, dtype: int64

In [25]:
#check variable type
df_sample.dtypes

id              str
caption         str
schema          str
first_seen      str
last_seen       str
               ...
mainCountry     str
icijId          str
postalCode      str
model           str
serialNumber    str
Length: 103, dtype: object

In [26]:
df_sample.describe(include="all")

,id,caption,schema,first_seen,last_seen,last_change,target,datasets,referents_count,startDate,...,mmsi,vatCode,wikidataId,percentage,sharesCount,mainCountry,icijId,postalCode,model,serialNumber
count,1000,1000,1000,1000,1000,1000,1000,1000,1000.000000,480,...,2,1,1,2,1,1,2,1,1,1
unique,1000,252,12,182,56,97,2,140,NaN,272,...,2,1,1,2,1,1,2,1,1,1
top,NK-2229ydxkHNa5AcDp9d6jt3,Occupancy,Occupancy,2025-12-09T10:14:09,2026-03-02T00:12:02,2026-01-16T00:12:01,False,"wd_peps, wd_categories",NaN,2014-03-23,...,352002470,BE0686.896.689,Q11146224,1,100,cy,82009540,659300,A310-304,524
freq,1,662,662,309,629,455,804,597,NaN,15,...,1,1,1,1,1,1,1,1,1,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.326000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.112187,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
#checking missing values
missing = df_sample.isnull().sum() / len(df_sample) * 100
missing = missing[missing > 0].sort_values(ascending=False)

print("Features with missing values (% missing):")
print(missing.round(1))

Features with missing values (% missing):
serialNumber        99.9
wikidataId          99.9
brightQueryId       99.9
brightQueryOrgId    99.9
hairColor           99.9
                    ...
status              77.2
name                75.8
startDate           52.0
post                33.8
holder              33.8
Length: 94, dtype: float64

In [29]:
#look for the most complete variable
missing.tail(20)

sector         94.5
sourceUrl      94.3
position       93.6
successor      93.1
predecessor    93.1
alias          93.0
lastName       91.9
firstName      91.9
birthDate      91.0
createdAt      87.9
programId      86.3
address        82.3
country        81.8
endDate        81.5
topics         78.0
status         77.2
name           75.8
startDate      52.0
post           33.8
holder         33.8
dtype: float64

In [30]:
#understand schemas vs properties
df_sample.groupby("schema").size()

schema
Address           3
Airplane          1
Company          78
Directorship      4
Family           12
LegalEntity      21
Occupancy       662
Organization     33
Ownership         8
Person          102
Succession       69
Vessel            7
dtype: int64

In [31]:
#saving the flattened dataset
df_sample.to_csv("../../data/processed/sample_flattened.csv", index=False)